### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by cknitt** [cca-io/rescript-react-intl#11]
To use react-intl with react-native, one needs to pass the `Text` component to `IntlProvider`'s `textComponent` property:

```js
import { Text } from 'react-native';

<IntlProvider locale={locale} messages={messages} textComponent={Text}>
  ...
</IntlProvider>
```

This is not currently supported by the bs-react-intl bindings, because the `IntlProvider` binding expects `textComponent` to be of type `domTag`.

It can be worked around using `Obj.magic`:

```reason
[@bs.module "react-native"] external textComponent : ReasonReact.reactClass = "Text";
<ReactIntl.IntlProvider locale messages textComponent=(Obj.magic(textComponent))>
  ...
</ReactIntl.IntlProvider>
```

But I do not see the benefits of the `domTag` variant anyway. I would propose to simply change the type of the `textComponent` to `'a`, or alternatively use a variant:

```reason
type textComponent =
  | DomTag(string)
  | ReactComponent(ReasonReact.reactClass);
```

@alexfedoseev Please let me know which way you want to go, then I can prepare a PR.

**Comment by alex35mil** [comment]
@cknitt I missed a lot of stuff in July incl. this issue. Sorry for that! `'a` sounds good to me 👍

**Comment by cknitt** [comment]
See #13. I have kept the `domTag` type after all and have now

```reason
type textComponent =
  | DomTag(domTag)
  | ReactComponent(ReasonReact.reactClass);
```
