### ISSUE TITLE
IntlProvıder's locale property doesn't work correctly, I had to provide it with static locale string to work

### ISSUE THREAD

**Issue by esonhey** [cca-io/rescript-react-intl#18]

**Comment by alex35mil** [comment]
@ehsanheydariyk I'm not sure I follow, can you post gist or something?

**Comment by alex35mil** [comment]
[Here](https://github.com/alexfedoseev/bs-react-intl/blob/master/examples/App.re#L17) locale is passed as dynamic value and it works.
