### ISSUE TITLE
Replace `IntlInjector.js` w/ something REasonable

### ISSUE THREAD

**Issue by alex35mil** [cca-io/rescript-react-intl#2]
ATM `injectIntl` is implemented using JS layer: https://github.com/alexfedoseev/bs-react-intl/blob/master/src/IntlInjector.js

It causes issues with specific configurations of BS target & bundlers.

Ideally, this FFI should be implemented fully in reason.

**Comment by cknitt** [comment]
I just ran into this issue when building with `react-scripts`. (`IntlInjector.js` is not found.)

I can offer the following quick and dirty solution:

* Remove IntlInjector.js.
* In ReactIntl.re, do:

```re
module IntlInjector = {
  let reactClass: ReasonReact.reactClass = [%bs.raw
    {|
    require("react-intl").injectIntl(function(_ref) {
      var intl = _ref.intl, children = _ref.children;
      return children(intl);
    })
    |}
  ];
  let make = children =>
    ReasonReact.wrapJsForReason(~reactClass, ~props=Js.Obj.empty(), (intlJs: intlJs('t)) =>
      children(mapIntlJsToReason(intlJs))
    );
};
```

Basically it inlines your current implementation into ReactIntl.re.

Would you like a PR for that?

**Comment by alex35mil** [comment]
This workaround LGTM 👍 

Link to [another approach](https://medium.com/@_gabrielrubens/binding-a-react-hoc-to-reasonml-children-as-function-d2688e4edaae), but I haven't looked into details of this, not sure if it's suitable or not.

**Comment by cknitt** [comment]
@alexfedoseev I have implemented the workaround I suggested in #6 and would be happy to get it merged. I haven't had time to look into the other approach in detail yet.

**Comment by alex35mil** [comment]
@cknitt `bs-react-intl 0.2.1 published` Thanks!

**Comment by AndreaZChen** [comment]
This solution still causes issues with "specific configurations of BS target & bundlers", sadly. To be precise: I use ES6 modules in my project and I use Rollup for bundling. Rollup does not allow mixing `require` statements with `import`/`export` statements, so by inlining `require`  into the file, it becomes impossible to bundle it using Rollup unless I reconfigure my project to use CommonJS.

If it's possible, it would be nice to look into a solution that is agnostic with regards to module format (i.e. doesn't use a raw `require`).

**Comment by alex35mil** [comment]
@AndreaZChen If you’re using hooks API, I can offer a temporary solution. It’s not public yet but let me know if you’re interested, I’ll make it consumable.

**Comment by alex35mil** [comment]
https://github.com/alexfedoseev/bs-react-intl/pull/20
