### ISSUE TITLE
Repo and package name

### ISSUE THREAD

**Issue by cknitt** [cca-io/rescript-react-intl#39]
@alexfedoseev How shall we go about renaming the repo and npm package?

My suggestion would be to release the next version as rescript-react-intl 3.0.0 and rename the repo to rescript-react-intl, too. But what about the reasonml-community organization? Do you know if it going to be renamed to rescript-community at some point? Otherwise should we move to another org?

Alternatively, we could also create a rescript-react-intl org and put both this repo and the extractor there.

**Comment by cknitt** [comment]
@alexfedoseev There won't be a rescript-community org, see https://forum.rescript-lang.org/t/github-organization-reasonml-community-rescript-community/1630/2.

So I would suggest that we move the repo either to a new rescript-react-intl org or to your or our (cca-io) company org. What do you think?

**Comment by ryyppy** [comment]
I'd be in favour of moving it under the CCA organization for marketing reasons. Way easier to commit on a library that is owned by a company brand.

Also, maybe it would be worth thinking about merging the bs-react-intl + bs-react-intl-extractor-bin repositories in one unified `rescript-react-intl` repo?

I don't see why those repos should be separated... makes things harder to track down when there's api changes. If you want to share ownership, it's easy to add others as explicit contributors / owners.

For npm publishing, there can still be two separate packages for the lib, and the extractor.

**Comment by alex35mil** [comment]
> So I would suggest that we move the repo either to a new rescript-react-intl org or to your or our (cca-io) company org. What do you think?

Either is fine with me. Having own org for this package doesn't make a lot of sense imo so CCA seems like a better option.

> I don't see why those repos should be separated... makes things harder to track down when there's api changes. If you want to share ownership, it's easy to add others as explicit contributors / owners.

@ryyppy The goal was to eventually merge these 2 repos but it wasn't done yet due to lack of time.

**Comment by cknitt** [comment]
@ryyppy It seems I do not have the rights to rename or move the repo.

Could you initiate a transfer to the cca-io organization?

**Comment by cknitt** [comment]
Ah, something else, @alexfedoseev, regarding authorship and license: Currently you are listed as the author and MIT license is set in the package.json.

Would it be ok if I added an (MIT) license file listing both me and you as authors, and if I set myself as author and you as contributor in the package.json (or vice versa) as it seems it is not possible to have multiple authors in package.json?

**Comment by alex35mil** [comment]
Of course!

**Comment by cknitt** [comment]
Transfered to cca-io/rescript-react-intl as dicussed.

**Comment by cknitt** [comment]
Released rescript-react-intl 3.0.0.
