### ISSUE TITLE
description prop

### ISSUE THREAD

**Issue by cknitt** [cca-io/rescript-react-intl#5]
In react-intl, `FormattedMessage` accepts an optional `description` prop. Also (see https://github.com/yahoo/react-intl/wiki/Components#message-descriptor),

```js
type MessageDescriptor = {
    id: string,
    defaultMessage?: string,
    description?: string | object,
};
```

has the optional description field, too, and the defaultMessage seems to be optional as well.

In Reason, we currently have

```re
type message = {
  .
  "id": string,
  "defaultMessage": string,
};
```

How would we model the two optional fields? I think we would need a `makeMessage(Descriptor)` function with two optional labeled parameters.

And how do we model the fact that description may be either string or object? `[@bs.unwrap]` (https://bucklescript.github.io/docs/en/function.html#trick-2-polymorphic-variant-bsunwrap)?

**Comment by alex35mil** [comment]
At the very beginning, I chose not to think about it b/c it seems a hard problem to solve w/o introducing a new type & component :)

**Comment by cknitt** [comment]
Solved in the extractor for now: https://github.com/cknitt/bs-react-intl-extractor/pull/62.
